networks:
  lecoursier:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    networks:
      - default
      - lecoursier
    volumes:
      - .:/var/www/html
    ports:
      - 80:8080
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.app.rule=Host(`lecoursier.local`)"
    #   - "traefik.http.services.app.loadbalancer.server.port=8080"
    #   - "traefik.http.routers.app.entrypoints=web"
    #   - "traefik.docker.network=lecoursier"
