networks:
  lecoursier:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    networks:
      - default
      - lecoursier
    volumes:
      - .:/var/www/html
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - default
      - lecoursier
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
