# Push docker image to Docker Hub
name: Push Docker Image Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t lecoursier-laravel-staging .

      - name: Push Docker Image
        run: |
          docker tag lecoursier-laravel ${{ secrets.DOCKER_USERNAME }}/lecoursier-laravel-staging:latest
          docker tag lecoursier-laravel ${{ secrets.DOCKER_USERNAME }}/lecoursier-laravel-staging:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/lecoursier-laravel-staging:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/lecoursier-laravel-staging:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout
