name: Test check Workflow for PRs

on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2
          coverage: xdebug

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.test.actions.example', '.env');"

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate key
        run: |
          php artisan key:generate
          php artisan config:clear

      - name: Run tests
        id: run-tests
        run: ./vendor/bin/pest --ci --coverage --min=30

      - name: Send test failure email
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ Tests failed - ${{ github.workflow }}"
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: "GitHub Actions - Le Coursier"
          body: |
            ❌ The tests failed when trying to merge the PR.
            - Pipeline: ${{ github.workflow }}
            - PR: ${{ github.event.pull_request.html_url }}
            - Branch: ${{ github.event.pull_request.head.ref }}
            - Commit: ${{ github.event.pull_request.head.sha }}

            Please check the PR and fix the issues.
            🔗 Workflow Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
