name: Update Submodule in Main Repo

on:
  push:
    branches:
      - master

jobs:
  update-main-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Main Repo
        uses: actions/checkout@v3
        with:
          repository: JoseMokeni/PFE
          token: ${{ secrets.PAT_FOR_MAIN_REPO }}
          ref: master

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update submodule pointer
        run: |
          cd lecoursier-laravel

          git fetch origin

          # Now check out the specific commit that triggered this push.
          # GITHUB_SHA is provided by default in the workflow environment.
          # That means the submodule pointer will be updated to exactly the commit of this push.
          git checkout $GITHUB_SHA

          # Return to the main repo root
          cd ..

          # Stage the submodule change
          git add lecoursier-laravel

          # Commit the pointer update
          git commit -m "chore: update submodule pointer to commit $GITHUB_SHA"

      # 4. Push changes back to the main repo
      - name: Push update to Main Repo
        run: |
          git push origin master
